## 기초데이터과학 (01분반) 

## Programming assignment 01

### 1. numpy를 사용하여 정수값을 갖는 4x4 배열에서 최대값의 위치(좌표)와 최소값의 위치(좌표)를 출력하는 코드를 작성하시오.

In [35]:
import numpy as np

# 4x4 배열 생성
arr = np.array([[10, 15, 30, 40],
                [50, 60, 70, 80],
                [90, 95, 85, 75],
                [65, 55, 45, 35]])

# 최대값, 최소값의 인덱스 - numpy의 argmax, argmin 함수 사용



# argmax, argmin 함수의 결과로 나온 인덱스를 4x4 배열에서의 위치로 변환 - numpy의 unravel_index 함수 사용
# unravel_index 함수 사용법은 검색하여 각자 찾아서 해볼 것



# 결과 출력



##### 아래의 출력처럼 결과가 나와야 함 #####

최대값 인덱스: 9
4x4 배열에서의 최대값 위치: (2, 1)
최소값 인덱스: 0
4x4 배열에서의 최소값 위치: (0, 0)


### 2. 1부터 50까지의 숫자를 가진 numpy 배열을 생성하고, 그 배열에서 짝수만 추출하여 출력하는 코드를 작성하시오.

In [34]:
import numpy as np

# 1부터 50까지의 숫자를 가진 numpy 배열 생성


# 위 배열에서 짝수인 것은 True, 홀수인 것은 False 값을 갖도록 하여 출력


# 위 배열에서 짝수인 것의 개수 출력



# 짝수만 추출 - 배열에 조건식을 사용하는 방법으로 짝수만 포함하는 배열 생성


# 짝수만 추출한 결과 출력


##### 아래의 출력처럼 결과가 나와야 함 #####

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True]
25
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


### 3. 30 이하 양의 정수에서 짝수만 원소로 갖는 1차원 배열을 생성하고, 이를 3x5 형태의 2차원 배열로 재구성하시오. 그 다음, 각 원소를 최솟값 0, 최댓값 1 사이로 정규화(Min-Max) 하는 코드를 작성하시오.

In [2]:
import numpy as np

# 30 이하 양의 짝수를 가진 1차원 배열 생성 및 출력



# 1차원 배열을 3행 5열의 2차원 배열로 변환 및 출력



# Min-Max 정규화



# 정규화된 배열 출력


1차원 배열:
 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
2차원 배열:
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
Min-Max 정규화된 배열:
 [[0.         0.07142857 0.14285714 0.21428571 0.28571429]
 [0.35714286 0.42857143 0.5        0.57142857 0.64285714]
 [0.71428571 0.78571429 0.85714286 0.92857143 1.        ]]


### 4. 평균 0, 표준편차 1인 정규분포를 따르는 10,000개의 숫자를 포함하는 배열을 생성하고, 그 배열의 평균과 표준편차를 계산하는 코드를 작성하시오.

In [32]:
import numpy as np

# 평균 0, 표준편차 1인 정규분포로 이루어진 10,000개의 숫자를 포함하는 1차원 배열 생성 
# numpy의 random.randn 함수 또는 random.normal 함수 사용



# 배열의 평균과 표준편차 계산


# 결과 출력


##### 랜덤 값을 갖는 배열을 생성하기 때문에 아래의 출력과 동일하게 나오지 않을 수 있음 #####

배열의 평균: -0.014092001687723774
배열의 표준편차: 1.0053163958999263


### 5. 1부터 10까지 임의의 정수를 원소로 갖는 4x4 배열을 랜덤하게 생성한 후, 배열 내에서 8보다 큰 원소의 개수와 3보다 작은 원소의 개수를 출력하는 코드를 작성하시오.

In [31]:
import numpy as np

# 1부터 10까지 임의의 정수값을 갖는 4x4 numpy 배열 생성 - random.randint 함수 사용


# 생성된 배열 출력


# 8보다 큰 원소의 개수 출력


# 3보다 작은 원소의 개수 출력


##### 랜덤 값을 갖는 배열을 생성하기 때문에 아래의 출력과 동일하게 나오지 않을 수 있음 #####

[[9 1 3 8]
 [9 2 5 2]
 [9 8 1 6]
 [1 5 3 6]]
8보다 큰 원소의 개수: 3
3보다 작은 원소의 개수: 5
